package com.practicas.util;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

public class DatabaseInstaller {

    private final Connection conn;

    public DatabaseInstaller(Connection conn) {
        this.conn = conn;
    }

    public void crearTablas() throws SQLException {
        Statement st = conn.createStatement();

        st.executeUpdate("""
            CREATE TABLE USUARIO (
                ID_USUARIO NUMBER GENERATED BY DEFAULT AS IDENTITY,
                NOMBRE VARCHAR2(100) NOT NULL,
                APELLIDO VARCHAR2(100) NOT NULL,
                EMAIL VARCHAR2(150) NOT NULL,
                PASSWORD_HASH VARCHAR2(255) NOT NULL,
                ROL VARCHAR2(30) NOT NULL,
                ACTIVO NUMBER(1) DEFAULT 1,
                TELEFONO VARCHAR2(30),
                FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO),
                CONSTRAINT UK_USUARIO_EMAIL UNIQUE (EMAIL)
            )
        """);

        st.executeUpdate("""
            CREATE TABLE INSTITUCION_RECEPTORA (
                ID_INSTITUCION NUMBER GENERATED BY DEFAULT AS IDENTITY,
                NOMBRE VARCHAR2(150) NOT NULL,
                NIT VARCHAR2(50) NOT NULL,
                DIRECCION VARCHAR2(200),
                MUNICIPIO VARCHAR2(100),
                DEPARTAMENTO VARCHAR2(100),
                TELEFONO VARCHAR2(30),
                EMAIL_CONTACTO VARCHAR2(150),
                CONVENIO_ACTIVO NUMBER(1) DEFAULT 1,
                FECHA_CONVENIO DATE,
                CONSTRAINT PK_INSTITUCION PRIMARY KEY (ID_INSTITUCION),
                CONSTRAINT UK_INSTITUCION_NIT UNIQUE (NIT)
            )
        """);

        st.executeUpdate("""
            CREATE TABLE PRACTICA (
                ID_PRACTICA NUMBER GENERATED BY DEFAULT AS IDENTITY,
                NOMBRE VARCHAR2(150) NOT NULL,
                DESCRIPCION VARCHAR2(500),
                NUMERO_PRACTICA NUMBER(2) NOT NULL,
                HORAS_REGLAMENTARIAS NUMBER(5),
                FECHA_INICIO DATE,
                FECHA_FIN DATE,
                ESTADO VARCHAR2(30),
                TIPO_PRACTICA VARCHAR2(100),
                FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT PK_PRACTICA PRIMARY KEY (ID_PRACTICA)
            )
        """);

        st.executeUpdate("""
            CREATE TABLE GRUPO_PRACTICA (
                ID_GRUPO NUMBER GENERATED BY DEFAULT AS IDENTITY,
                NOMBRE VARCHAR2(100) NOT NULL,
                ID_PRACTICA NUMBER NOT NULL,
                ID_DOCENTE NUMBER NOT NULL,
                ID_INSTITUCION NUMBER NOT NULL,
                CUPO_MAXIMO NUMBER(5),
                OBSERVACIONES VARCHAR2(500),
                CONSTRAINT PK_GRUPO PRIMARY KEY (ID_GRUPO),
                CONSTRAINT FK_GRUPO_PRACTICA FOREIGN KEY (ID_PRACTICA) REFERENCES PRACTICA(ID_PRACTICA),
                CONSTRAINT FK_GRUPO_DOCENTE FOREIGN KEY (ID_DOCENTE) REFERENCES USUARIO(ID_USUARIO),
                CONSTRAINT FK_GRUPO_INSTITUCION FOREIGN KEY (ID_INSTITUCION) REFERENCES INSTITUCION_RECEPTORA(ID_INSTITUCION)
            )
        """);

        st.executeUpdate("""
            CREATE TABLE INSCRIPCION_GRUPO (
                ID_INSCRIPCION NUMBER GENERATED ALWAYS AS IDENTITY,
                ID_ESTUDIANTE NUMBER NOT NULL,
                ID_GRUPO NUMBER NOT NULL,
                HORAS_CUMPLIDAS NUMBER(8,2) DEFAULT 0,
                ESTADO VARCHAR2(30),
                FECHA_INSCRIPCION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                OBSERVACION_FINAL VARCHAR2(500),
                CONSTRAINT PK_INSCRIPCION_GRUPO PRIMARY KEY (ID_INSCRIPCION),
                CONSTRAINT FK_INSCRIPCION_ESTUDIANTE FOREIGN KEY (ID_ESTUDIANTE) REFERENCES USUARIO(ID_USUARIO),
                CONSTRAINT FK_INSCRIPCION_GRUPO FOREIGN KEY (ID_GRUPO) REFERENCES GRUPO_PRACTICA(ID_GRUPO)
            )
        """);

        st.executeUpdate("""
            INSERT INTO USUARIO (NOMBRE, APELLIDO, EMAIL, PASSWORD_HASH, ROL, ACTIVO)
            VALUES ('GestionP', 'Admin', 'GestionP', 'GestionP', 'ADMIN', 1)
        """);

        st.close();
    }

    public void borrarTablas() throws SQLException {
        Statement st = conn.createStatement();
        try { st.executeUpdate("DROP TABLE INSCRIPCION_GRUPO CASCADE CONSTRAINTS"); } catch (Exception e) {}
        try { st.executeUpdate("DROP TABLE GRUPO_PRACTICA CASCADE CONSTRAINTS"); } catch (Exception e) {}
        try { st.executeUpdate("DROP TABLE PRACTICA CASCADE CONSTRAINTS"); } catch (Exception e) {}
        try { st.executeUpdate("DROP TABLE INSTITUCION_RECEPTORA CASCADE CONSTRAINTS"); } catch (Exception e) {}
        try { st.executeUpdate("DROP TABLE USUARIO CASCADE CONSTRAINTS"); } catch (Exception e) {}
        st.close();
    }
}
